# Generated by Django 4.2.3 on 2023-07-09 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='cac_file',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='government_id',
        ),
    ]
