# Generated by Django 4.0.3 on 2022-12-24 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='in_stock',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(help_text='format: required', on_delete=django.db.models.deletion.PROTECT, related_name='product', to='products.category', verbose_name='category'),
        ),
    ]
